import type { EnvVarSpec } from "./types";

export const oidcEnv: readonly EnvVarSpec[] = [
  {
    name: "OIDC_ISSUER_URL",
    group: "OIDC",
    kind: "string",
    requiredWhenOidcEnabled: true,
    doc: "OIDC issuer (provider) base URL.",
    example: "https://auth.example.com/realms/main",
  },
  {
    name: "OIDC_CLIENT_ID",
    group: "OIDC",
    kind: "string",
    requiredWhenOidcEnabled: true,
    doc: "OIDC client identifier.",
  },
  {
    name: "OIDC_REDIRECT_URI",
    group: "OIDC",
    kind: "string",
    requiredWhenOidcEnabled: true,
    doc: "OIDC redirect URI; must be HTTPS in production.",
    example: "https://excalidash.example.com/auth/oidc/callback",
  },
  {
    name: "OIDC_DISCOVERY_URL",
    group: "OIDC",
    kind: "string",
    doc: "Explicit OIDC discovery document URL (overrides issuer-derived path).",
  },
  {
    name: "OIDC_CLIENT_SECRET",
    group: "OIDC",
    kind: "string",
    secret: true,
    doc: "OIDC client secret for confidential clients.",
  },
  {
    name: "OIDC_PROVIDER_NAME",
    group: "OIDC",
    kind: "string",
    default: "OIDC",
    doc: "Display name of the OIDC provider shown in the UI.",
  },
  {
    name: "OIDC_SCOPES",
    group: "OIDC",
    kind: "string",
    default: "openid profile email",
    doc: "Space-separated OIDC scopes requested during login.",
  },
  {
    name: "OIDC_EMAIL_CLAIM",
    group: "OIDC",
    kind: "string",
    default: "email",
    doc: "ID-token claim to read the user email from.",
  },
  {
    name: "OIDC_EMAIL_VERIFIED_CLAIM",
    group: "OIDC",
    kind: "string",
    default: "email_verified",
    doc: "ID-token claim indicating whether the email is verified.",
  },
  {
    name: "OIDC_ALLOWED_EMAILS",
    group: "OIDC",
    kind: "csv",
    doc: "Optional comma-separated allow-list of verified email addresses permitted to sign in.",
  },
  {
    name: "OIDC_GROUPS_CLAIM",
    group: "OIDC",
    kind: "string",
    default: "groups",
    doc: "ID-token claim (key or path) carrying the user's groups.",
  },
  {
    name: "OIDC_ADMIN_GROUPS",
    group: "OIDC",
    kind: "csv",
    doc: "Comma-separated groups whose members are granted admin.",
  },
  {
    name: "OIDC_REQUIRE_EMAIL_VERIFIED",
    group: "OIDC",
    kind: "boolean",
    default: "true",
    doc: "Reject logins whose email is not marked verified.",
  },
  {
    name: "OIDC_JIT_PROVISIONING",
    group: "OIDC",
    kind: "boolean",
    default: "true",
    doc: "Just-in-time provision users on first successful OIDC login.",
  },
  {
    name: "OIDC_FIRST_USER_ADMIN",
    group: "OIDC",
    kind: "boolean",
    default: "true",
    doc: "Grant admin to the first user provisioned via OIDC.",
  },
  {
    name: "OIDC_ID_TOKEN_SIGNED_RESPONSE_ALG",
    group: "OIDC",
    kind: "enum",
    values: [
      "RS256",
      "RS384",
      "RS512",
      "PS256",
      "PS384",
      "PS512",
      "ES256",
      "ES384",
      "ES512",
      "EdDSA",
      "HS256",
      "HS384",
      "HS512",
    ],
    doc: "Expected signing algorithm for the ID token.",
  },
  {
    name: "OIDC_TOKEN_ENDPOINT_AUTH_METHOD",
    group: "OIDC",
    kind: "enum",
    values: ["none", "client_secret_basic", "client_secret_post"],
    doc: "Client authentication method used at the token endpoint.",
  },
];
